-- EJERCICIO 1 : https://gist.github.com/DavidBernalGonzalez/b31524c01cb40028841292fa4a25be61
-- SELECT * FROM myTable WHERE phone LIKE '(811)%';
-- SELECT * FROM myTable WHERE country = 'Italy' OR country = 'Spain';
-- SELECT count(id) FROM myTable;
-- SELECT * FROM myTable WHERE id IN (SELECT id FROM myTable WHERE country = 'Germany' OR country = 'Turkey');
-- SELECT max(id), min(id) FROM myTable;
-- SELECT count(id), country FROM mytable GROUP BY country;
-- SELECT * FROM mytable ORDER BY postalZip ASC LIMIT 10;Ç
-- DELETE FROM mytable WHERE country = 'Singapore';	